### ISSUE TITLE
(urgent) Use Glossarist gem instead of manual splitting (`split_codes.rb`) to generate Metanorma AsciiDoc

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/iev-document#6]
We are using complex input from IEV but the split_codes.rb script is very rudimentary.

e.g.
```yaml
eng:
  id: 192-01-03
  terms:
  - type: expression
    normative_status: preferred
    usage_info: in dependability
    designation: system
  definition: set of interrelated items that collectively fulfil a requirement
  language_code: eng
  notes:
  - A system is considered to have a defined real or abstract boundary.
  - External resources (from outside the system boundary) may be required for the
    system to operate.
  - A system structure may be hierarchical, e.g. system, subsystem, component, etc.
  - Conditions of use and maintenance should be expressed or implied within the requirement.
  examples: []
  entry_status: valid
  authoritative_source:
  - ref: IEC 60050-151:2001
    clause: 151-11-27
    link: https://webstore.iec.ch/publication/176
    relationship:
      type: modified
      modification: by extension to suit the dependability context
    original: IEC 60050-151:2001, 151-11-27, modified by extension to suit the dependability
      context
  date_accepted: '2015-02-01T00:00:00+00:00'
  date_amended: '2015-02-01T00:00:00+00:00'
  review_date: '2015-02-01T00:00:00+00:00'
  review_decision_date: '2015-02-01T00:00:00+00:00'
  review_decision_event: published
```

Metanorma has been updated to use the Glossarist gem so we just need to add a `GlossaristConcept.new.to_mnadoc` method.

See: https://www.metanorma.org/author/topics/document-format/section-terms/
